name: proyecto_moviles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  google_maps_flutter: ^2.5.0
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^8.1.2
  image_picker: ^1.0.4
  file_picker: ^5.2.5
  easy_pdf_viewer: ^1.0.6
  table_calendar: ^3.0.9
  http_services: ^2.1.1
  firebase_storage: ^11.5.2
  provider: ^6.0.5
  intl: ^0.18.1
  email_validator: '^2.1.16'
  art_sweetalert: ^0.0.5
  http: ^0.13.6
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  google_sign_in: ^6.1.6
  sn_progress_dialog: ^1.1.3
  awesome_dialog: ^3.0.2
  day_night_switcher: ^0.2.0+1
  lottie: ^2.6.0
  concentric_transition: ^1.0.3
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  social_login_buttons: ^1.0.7
  firebase_messaging: ^14.7.6
  firebase_app_installations: ^0.2.4+6
  github_sign_in_plus: ^0.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/animation/.
