name: proyecto_moviles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  email_validator: ^2.0.1
  social_login_buttons: ^1.0.7
  awesome_dialog: ^3.1.0
  sn_progress_dialog: ^1.0.1
  http: ^1.1.0
  sqflite: ^2.3.0
  day_night_switcher: ^0.2.0+1
  lottie: ^2.6.0
  shared_preferences: ^2.2.1
  concentric_transition: ^1.0.3
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  provider: ^6.0.5
  intl: ^0.18.1
  art_sweetalert: ^0.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
